server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /api

spring:
  profiles:
    activate: dev

  application:
    name: interview-mirror-backend
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_DATABASE:interview_db}
    username: ${DB_USER:root}
    password: ${MYSQL_ROOT_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: true
  cache:
    type: redis
    redis:
      time-to-live: 1800000
  redis:
    host: ${REDIS_HOST:127.0.0.1}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}
    timeout: 2000

logging:
  level:
    root: INFO
    com.interviewmirror: INFO

springdoc:
  api-docs:
    path: /v1/api-docs
  swagger-ui:
    path: /swagger-ui.html
