spring:
  config:
    activate:
      on-profile: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:interview_db}?serverTimezone=Asia/Seoul
    username: ${DB_USER:root}
    password: ${MYSQL_ROOT_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: never

  cache:
    type: none

  redis:
    host: ${REDIS_HOST:127.0.0.1}
    port: ${REDIS_PORT:6379}

logging:
  level:
    root: INFO
    com.interviewmirror: DEBUG
    org.hibernate.SQL: DEBUG
