server:
  port: ${SERVER_PORT:8080}
  forward-headers-strategy: framework
  servlet:
    context-path: /api

spring:
  profiles:
    default: dev

  application:
    name: interview-mirror-backend

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:interview_mirror}?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Seoul
    username: ${MYSQL_USER:root}
    password: ${MYSQL_ROOT_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  cache:
    type: redis
    redis:
      time-to-live: 1800000
  data:
    redis:
      host: ${REDIS_HOST:127.0.0.1}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: 2000

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            google:
              redirect-uri: "https://cameron-hereditary-suppositively.ngrok-free.dev/api/login/oauth2/code/google"
            scope:
              - email
              - profile

grpc:
  client:
    ai-server:
      address: "static://${AI_SERVER_HOST:localhost}:${AI_SERVER_PORT:50051}"
      negotiation-type: ${GRPC_NEGOTIATION_TYPE:plaintext}

realtime:
  buffer:
    ttl: PT2H
    flush-interval-ms: 2000
    max-size-per-session: 1000

logging:
  level:
    root: INFO
    com.interviewmirror: INFO

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY:dummy} # 환경변수에서 로드
      secret-key: ${AWS_SECRET_KEY:dummy} # 환경변수에서 로드
    region:
      static: ap-northeast-2 # 서울 리전 (보통 고정해서 사용)
    s3:
      bucket: ${S3_BUCKET_NAME:dummy_name} # 사용할 S3 버킷 이름
    stack:
      auto: false # 로컬/일반 서버 실행 시 EC2 메타데이터 체크 방지

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration-ms: ${JWT_ACCESS_TOKEN_EXPIRATION_MS}
  refresh-token-expiration-ms: ${JWT_REFRESH_TOKEN_EXPIRATION_MS}

oauth:
  success-redirect-url: ${OAUTH_SUCCESS_REDIRECT_URL}
  code-expiration-ms: ${OAUTH_CODE_EXPIRATION_MS}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:}
